name: Docker Image Build

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.Dockerfile'
      - '**.yml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      #- '**.Dockerfile'
      - '**.yml'

jobs:
  get-changed-dockerfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            *.Dockerfile
          json: true
          json_raw_format: true


    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}

  build-and-push-images:
    if: ${{ fromJson(needs.get-changed-dockerfiles.outputs.matrix) }}
    needs:
      - get-changed-dockerfiles
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.get-changed-dockerfiles.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v3

    - uses: docker/setup-qemu-action@v2

    - uses: docker/setup-buildx-action@v2

    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64
        file: ${{ matrix.file }}
        push: true
        tags: andrjohns/revdeps
        cache-from: type=gha
        cache-to: type=gha,mode=max
