name: Docker Image Build

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.Dockerfile'
      - '**.yml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      #- '**.Dockerfile'
      - '**.yml'

jobs:
  get-changed-dockerfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            *.Dockerfile
            **/*.Dockerfile
            **/Dockerfile*
          files_ignore: |
            **/Dockerfiles.js
          json: true
          json_raw_format: true

      - name: Generate args matrix
        uses: actions/github-script@v6
        id: generator
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const make_args_matrix = require(`${process.env.GITHUB_WORKSPACE}/Dockerfiles.js`)
            return make_args_matrix(${{ steps.changed-files.outputs.all_changed_files }});

    outputs:
      matrix: ${{ steps.generator.outputs.result }}

  build-and-push-images:
    name: Build and Push ${{ matrix.tag }}
    if: ${{ fromJson(needs.get-changed-dockerfiles.outputs.matrix) }}
    needs:
      - get-changed-dockerfiles
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-changed-dockerfiles.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      if: matrix.platforms != 'linux/amd64'
      uses: docker/setup-qemu-action@master

    - uses: docker/setup-buildx-action@master

    - uses: docker/login-action@master
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Download build files
      if: matrix.tag == 'andrjohns/sem'
      run: wget "${{ secrets.MPLUS_DOWNLOAD_URL }}" -O ComboLinux64.bin

    - uses: docker/build-push-action@v4
      with:
        platforms: ${{ matrix.platforms }}
        file: ${{ matrix.file }}
        push: true
        build-args: |-
          ${{ join(matrix.build_args, '
          ') }}
        tags: ${{ matrix.tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: "."
